self-hosted-runner:
  labels: []

paths:
  .github/workflows/*.yaml:
    ignore:
      - 'property "workflow_repository" is not defined in object type'
      - 'property "workflow_sha" is not defined in object type'
