name: test workflow

on:
  # workflow_call:
  #   inputs:
  #     image-tag: #얘가 버전일듯함
  #       required: true
  #       type: string
  #     environment:
  #       required: true
  #       type: string
  #     # 필요한 내용 사용처에서 보내주는 거 정리
  #       # 레포 이름
  #       # 릴리즈 노트 링크 https://github.com/alphaprime-dev/alphasquare-main-server/releases/tag/v23.1.0
  #       # 릴리즈 버전 image-tag
  #       # argocd 링크  https://argocd.alphasquare.co.kr/applications/data-server-prod
      
  
  push:
    branches: 
      - feat/notify-discord
  
jobs:

  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Create Discord Message
        id: message
        run: | 
          echo 'msg=
          ${{ toJSON('{
            "content": "hi", 
            "embeds": null, 
            "attachments": [] 
          }') }}  >> $GITHUB_OUTPUT

      - name: Send HTTP POST request
        run: echo ${{steps.message.outputs.msg}}
          
          
          # curl -X POST \
          # https://discord.com/api/webhooks/1062906330001723463/jFCyiTAA2Qi_427spFDTHQjQexN6d1Hwar63d2bz22xGDaBcwlm2pbHcwKnTtlw2_HxT \
          # -H 'Content-Type: application/json' \
          # -d $"{{steps.message.outputs.}}"


# "embeds": [
#               {
#                 "title": "Release Completed",
#                 "description": "---\n\n[alphaprime-dev/alphaprime-api-bot] version v0.5.1 image is pushed \n\n[Go to Argo CD](https://argocd.alphasquare.co.kr/applications/data-server-prod )\n\n---",
#                 "color": 5795484,
#                 "fields": [
#                   {
#                     "name": "Environment",
#                     "value": "PROD",
#                     "inline": true
#                   },
#                   {
#                     "name": "Repository",
#                     "value": "[alphaprime-api-bot](https://github.com/alphaprime-dev/alphasquare-main-server/tree/refs/tags/v23.1.0)",
#                     "inline": true
#                   },
#                   {
#                     "name": "Release Note",
#                     "value": "[v0.5.1](https://github.com/alphaprime-dev/alphaprime-api-bot/releases/tag/v0.5.1)",
#                     "inline": true
#                   }
#                 ],
#                 "author": {
#                   "name": "alphaprime-api-bot"
#                 }
#               }
#             ],