name: test workflow

on:
  # workflow_call:
  #   inputs:
  #     image-tag: #얘가 버전일듯함
  #       required: true
  #       type: string
  #     environment:
  #       required: true
  #       type: string
  #     # 필요한 내용 사용처에서 보내주는 거 정리
  #       # 레포 이름
  #       # 릴리즈 노트 링크 https://github.com/alphaprime-dev/alphasquare-main-server/releases/tag/v23.1.0
  #       # 릴리즈 버전 image-tag
  #       # argocd 링크  https://argocd.alphasquare.co.kr/applications/data-server-prod
      
  
  push:
    branches: 
      - feat/notify-discord
  
jobs:

  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
          python scripts/notify-discord.py


