name: test workflow

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      environment:
        required: true
        type: string
  
jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: alphaprime-dev/alpha-actions
          ref: feat/notify-discord
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install discord-webhook click
          python scripts/notify-discord.py \
          --env=${{ inputs.environment }} \
          --repo=${{ github.repository }} \
          --tag=${{ inputs.image-tag }}


