name: test workflow

on:
  workflow_call:
    inputs:
      image-tag: #얘가 버전일듯함
        required: true
        type: string
      environment:
        required: true
        type: string
  
  push:
    branches: 
      - feat/notify-discord
  
jobs:

  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          echo ${{ inputs.environment }}
          echo ${{ inputs.image-tag }}
          echo ${{ github.repository }}
          python -m pip install --upgrade pip
          pip install discord-webhook click
          python scripts/notify-discord.py --env=PROD --repo=alphasquare-main-server --tag=v22.22.0


