name: Reusable Workflow For Notify Discord

on:
  workflow_call:
    inputs:
      status: 
        required: true
        type: string
      environment:
        required: true
        type: string
      related-link:
        required: true
        type: string
      image-tag:
        required: true
        type: string
  
jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: alphaprime-dev/alpha-actions
          ref: ${{ github.workflow_sha }}
      - uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - run: |
          uv run python scripts/notify-discord.py \
          --webhook_url=${{ secrets.DISCORD_DEPLOY_WEBHOOK_URI }} \
          --status=${{ inputs.status }} \
          --env=${{ inputs.environment }} \
          --repo=${{ github.repository }} \
          --related_link="${{ inputs.related-link }}" \
          --tag=${{ inputs.image-tag }}
