name: PR Version Labeler

on:
  workflow_call:
  
  pull_request:
    types: [opened, edited]

jobs:
  version-labeler:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: alphaprime-dev/alpha-actions
          ref: main
      - uses: srvaroa/labeler@master
        with:
          config_path: .github/pr-version-labeler.yaml
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
