name: Get Image Tag By COMMIT SHA
on:
  workflow_call:
    outputs:
      image-tag:
        description: "IMAGE_TAG FROM COMMIT SHA"
        value: ${{ jobs.staging-image-tag.outputs.IMAGE_TAG }}

jobs:
  staging-image-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.IMAGE_TAG.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - id: IMAGE_TAG
        run: echo "IMAGE_TAG=staging-${{ steps.short-sha.outputs.sha }}" >> $GITHUB_OUTPUT
